name: "Cerrar Inactivos"

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v11
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Este issue ha sido marcado como inactivo porque no ha tenido actividad reciente.'
          stale-pr-message: 'Este PR ha sido marcado como inactivo porque no ha tenido actividad reciente.'
          days-before-stale: 60
          days-before-close: 7
